### ISSUE TITLE
Repo approval request Skordy-Cogs

### ISSUE THREAD

**Issue by Skordy** [Twentysix26/Red-Docs#16]
https://github.com/Skordy/Skordy-Cogs

Repository name: Skordy-Cogs
Author: Skordy
Description: Random assortment of cogs that make life easier.

**Comment by irdumbs** [comment]
the API usage looks a little.. shady
but besides that, looks fine.

**Comment by Twentysix26** [comment]
I'd like to point out that a lot of people freaked out about the guy who was developing (well, trying to make people do the job for him) a cog that did almost the same exact things and he was even banned for that. In fact, it's mostly the same cog, slightly edited and with some stuff added.

I don't have a problem with the tool themselves and like I pointed out back then, the reaction was exaggerated, but at least try to be coherent in deciding if you should +1 this one or not

**Comment by irdumbs** [comment]
The issue with that guy wasn't that he was trying to make a pair of binoculars.
The issue was that he was trying to make binoculars with materials that had the "sexual predator target" logo on it and then when asked why he wanted to using those tools, he never gave a straight answer.
After some prodding, he finally gave some info: "The people i'm with, we aren't like those sexual predators, we're the kind that expose scandals".
He got all uppity about us still not helping him, and subsequently got banned.

With that being said, I don't see any incoherence in the +1
If anybody can confirm that the API is malicious / not so nice, I'll remove it though 👍

**Comment by franc-ist** [comment]
@irdumbs API isn't malicious, however some commands don't work, mainly !upordown

**Comment by franc-ist** [comment]
Network tools is conflicting with Eslyium's application #17 . Please sort this out between yourselves.

**Comment by irdumbs** [comment]
conflicting 3rd party cogs aren't really an issue. the almost duplicate cogs are a little distasteful though. I'd like if they'd just combine their efforts and release 1 cog with 2 authors instead :wink:

**Comment by Skordy** [comment]
@irdumbs Already done.

**Comment by tekulvw** [comment]
Does not meet new 3 cog req, `Post` could have a bit more functionality. Denying beta application until more content is added, feel free to apply again at a later date.
