### ISSUE TITLE
Same's repo application (or something like that)

### ISSUE THREAD

**Issue by samppanja** [Twentysix26/Red-Docs#37]
List: beta

Repository name: [Pepsi-Cogs](https://github.com/pepsifire/Red-Cogs)

Author: [pepsifire](https://github.com/pepsifire) // Same#3094 on discord

Description: Various random cogs i mainly use for my bot, but felt like sharing them.

Applying for beta because i will mostly be improving these as the time goes by.

**Comment by franc-ist** [comment]
As far as I can tell, quotes is a copy of Will's quotes module. I suggest making a PR to his repo.

**Comment by samppanja** [comment]
Made the quotes.py use subcommands so it's definitely original code @FishyFing

**Comment by Redjumpman** [comment]
It's fine if you have a cog that does the same thing as someone else's cog, so long as the code is not the same. Enhancements and PRs are for red's core. People should have a choice, and it makes people work harder to improve their work to have the best X cog. That being said, here are a few critiques I have:
- You should change the name of your repo from Redcogs to like Pepsifire cogs. This allows us, and others know whose cogs their downloading. The last thing anyone needs in support is someone saying they have a broken red cog, and it turns out to be yours.
- You import discord a lot, and it's a pet peeve of mine. The only time you use "discord" is in your send msg cog. 
- Spruce up that readme! Give your cog users a way to contact you incase something breaks, or they have questions, want to contribute, etc. You could include this in your info JSON too.

**Comment by Eslyium** [comment]
Denied, I didnt think myself that some of these cogs are needed but keep going your doing really good though!

If you come out with anymore really nice ones feel free to reapply!
