### ISSUE TITLE
Suggestions regarding repos

### ISSUE THREAD

**Issue by palmtree5** [Twentysix26/Red-Docs#51]
After some discussion, we've come up with this:

**Cog creator role**

- Would help with voting on applications to be added to the list
- All users who currently have the role would get to keep the role. All future additions to the list need to be on the **approved** list to get the role

**Self moderating repos**
- Once a repo is on the list, the community would help moderate future additions and changes to those repos. This would best be accomplished by everyone on EITHER list having a channel with a webhook for their repo in [this server](https://discord.gg/GET4DVk)

**Cog promotion**
- This would be a spotlight of specific cogs with some sort of info about the cog along with instructions on how to install it
- This would be for both lists

@Kowlin @Redjumpman and @irdumbs contributed to the making of this suggestion

**Comment by Eslyium** [comment]
Alright, So.. Problems I see with this..
1. We really don't vote on who gets added to the Repo. This is done by staff or certain others who talk to staff in their spare time to download or check the code for any security issues or faults. (There is a reason why we never did a vote system)
2. While yes the cog promotion is nice.. Its honestly a bother. Unless someone is going to dedicate themselves to sitting there and changing it every single time. (who isn't going to be bias or w/e)

If you need more info feel free to PM me if need be.

**Comment by Redjumpman** [comment]
+1 for visability on this. How we approve applications should be streamlined and 26 should only need to view apps with high upvotes to decrease time sorting through and reviewing countless applications that need work. At the same time it is important to give back to those who have helped to expand the feature sets of Red by appealing to all sorts of communities. The beauty of Red is that even if you have a really niche server and need a specific thing for your bot, we likely have it through our repos.  That isnt really something you can find from other bots. Cog promotion helps marry two important aspects. Information about cogs that you might want on your server, and helping a content creator showcase his contributions. I urge that the points we discussed do not fall on deaf ears! If you have an opinion please join the converaation here!

**Comment by Redjumpman** [comment]
@Eslyium this wasn't a random post by @palmtree5. This is basically an organized post from a discussion in the RedCogs server, that irdumb said to put here for visability.

I think you may be getting lost in the weeds with what is being said about votes. 26 and the staff does not have enough manpower to test every cog in an app and to check for vulnerabilities, redundancies, trash, etc. These votes can limit only apps which have been vetted by cog creators to be reviewed. 

Also cog promotion doesnt have to be a third party opinion piece. It can be what it is, a promotion. Something written by the author. Put it on a 1 week rotating schedule to different approved repos. The current system to be put bluntly, blows. And we should be working towards a better system.

**Comment by Chovin** [comment]
I agree with this. 
The solutions provided may not be the best or easiest to maintain but they address issues and improvements with the community that I think should be addressed. The fact that the community has come together and formulated a plan to try to address those issues and improve the community... makes me all warm and fuzzy.

I agree with encouraging cog creators to review the code of repo apps. Implementing a system to help 26 get updates on app updates and cog creator +1's will take some effort. I am not opposed to starting the system now though.

One of the big problems with our current community is lack of communication. It's all word of mouth with no historical documentation. Having cog creators (not the role) have their own channels with github webhooked in would help greatly in getting them used to github, archiving, communicating ideas, notifying users, writing better code, etc

Cog promotion would get creators excited and working towards quality also. A spotlight would mean somebody would have to step up and curate it, doing interviews n such. 

I think these ideas are all improvements to the community. Please keep the communication here and not in PMs.

**Comment by Chovin** [comment]
Oh shoot didn't see the previous comment.
I was thinking a more curated list so that it actually means something to the creators if theirs gets a good critique, but that would take more manpower. An automated rotation could be a good fallback if we can't find a better solution

**Comment by Redjumpman** [comment]
This might also be a good forum to talk about having a community manager curate that list. That gives someone a position that has a clear role, doesnt need to mess with anything administrative, and helps to grow the community and promote Red.

**Comment by Chovin** [comment]
that's a lot of responsibility.
if anything, we could just start the role off as "the guy that does cog spotlights".
nor does it have to be 1 person.

**Comment by Redjumpman** [comment]
I dont think it is too much responsibility, but I think you make fair points. Didnt mean to detract from the original intent of this post. Haha
Anyone reading this forum please feel free to throw in opinions and generate conversation! Red has a great community, but we make it better with your help!

**Comment by NekoTony** [comment]
Maybe monthly promotional in the announcements channel

**Comment by skeith** [comment]
Instead of cog promotional, how about hall of fame? which require less updates while we formulize a better way for cog promotions

**Comment by NekoTony** [comment]
Naw, I kinda consider the approved repos as the hall of fame due to the unapproved repos with cogs out there. I'm still down for a weekly or monthly announcement from the official server about a choosed favorite and/or special styled-css repo on top of the approved list, for the favorite cog.

**Comment by Chovin** [comment]
could have a #spotlights channel or some such where these appear.
I think it should be in the Red Cogs server though. Seems appropriate.
It could go in the #announcements channel since we don't use that there. I'm a little bit leery of using that channel in case people end up not reading it and then an important security update happens

Themed spotlights? like "Community - Oriented", "Most Visually Appealing"
/shrug the organizer'd have to figure that out.

**Comment by skeith** [comment]
*meanwhile 26 mumbles "this is utter shit"

**Comment by Redjumpman** [comment]
I kinda understand having it in the RedCogs server, but an issue with that is getting people to join the server. It would go along way having an official nod that users should check that server out. I mentioned this before but nothing happened. Need info added in the cmd >repos saying that they should go to that server for questions and support instead of all these @ mentions in #support and DMs. 

But having the spotlight in the main server increases awareness. Any support veteran can tell you that most people don't even realize they can download all these other cogs. 

We should bridge thise two concepts so that the RedCogs server doesnt seem like a fringe experiment. Educating users by highlighting Red's expandability with spotlights, and propagating traffic to the server(RedCogs) by updating the support cmd >repos.

**Comment by Chovin** [comment]
oh shoot. 
- [ ] adding the server link to >repos and 
- [ ] to the docs in the custom cogs section  

would be perfect!  

@Twentysix26 and others, can we get 👍 s on this and 
- [ ] if there is no disagreement,  
- [ ] Twentysix has 👍 'd it, and
- [ ] 5 other people 👍  it,  

@Kowlin could you make the change?  

~~This change could be made regardless of decisions on the spotlight etc.~~  
**postponed** and will be made a separate issue when the single/multi-server decision is made

**Comment by Chovin** [comment]
I still think the spotlight should be in the cogs server though. It feels more organized that way and it also would feel more like it's is a community-driven thing. Also, I'm not sure where the spotlight would be if it was in the Red server. I think #announcements there should be reserved for large updates, important security updates, etc.

Keeping it only on the cogs server may start creating a rift between the servers though. if we could find ways to marry the servers..
maybe we could have the actual spotlight be in the Cogs server but whenever it happens, @ Red says in #coding, `@ username's xxx cog is being spotlighted in the Cogs server! <insert invite link>`

thoughts?

**Comment by Twentysix26** [comment]
I really like most of the ideas being proposed here. It's absolutely true that the workload is a lot and having the community screen them too would help. I simply don't have the time to do a thorough screen of every cog in every repo being posted here.  
The main worry I have:
A second server would fragment the community. I don't have a good solution for this. Making a lot of channels in the main server is absolutely messy and sadly there are no subchannels (yet?) on Discord.
This doesn't mean that I oppose the idea (as I said, I like it), I'm simply bringing up the point.  
Will elaborate further on the other points as I think about it

**Comment by Chovin** [comment]
just a small thing.
if all Red staff were in the Cogs server, it'd feel a lot more like the Cogs server was just a support/development place for Cogs in the same community and would dispel any feelings that it's a separate community in and of itself.

![image](https://cloud.githubusercontent.com/assets/17536161/20249243/03f78b96-aa41-11e6-8391-6b25d5f185df.png)

it is mainly a support server, so you don't _have_ to watch all the channels ;)

**Comment by Kowlin** [comment]
The reason the server was created to stop more fragmenting from occurring. We (Palm and I) wanted to keep cog support of the main server yet in a centralized place. We always have linked back any other support, like core bot support and coding questions to the main server. This would be the cleanest way of doing it in my opinion. I also think that fragmenting the server isn't a issue here, people will always join Red's primary server first for the support channels and other ways it gives. Having a sub-server speak off only takes of load from the primary server and spreads it out the appropriate channels.

For the spotlight, I think it would be the best to keep this in the primary server, I think the aim for the spot light is to expand the coding community and teach them, keeping in line with [meew0's best practices](https://github.com/meew0/discord-bot-best-practices).

**Comment by Twentysix26** [comment]
I had another idea. Since, as already discussed, having too many channels in the server would make things very messy (especially when joining the first time), how about making them opt-in instead? You'd need a role to see them. A role that you can autoassign to yourself through Red.  
Every cog author would moderate his own channel, a la Discord API server.  
Perhaps only the ones in the approved list could have their own channels and we could have a single one for beta repos? Thoughts? Downsides?

**Comment by Kowlin** [comment]
This can work in my opinion. But are you not afraid of role stacking? People will go through all hoops to get roles, even if they mean nothing. For moderation, authors can get manage_webhooks, manage_messages and manage_channels (of course all in a channel overwrite they own.)

**Comment by palmtree5** [comment]
IMO that could get messy having a single one for beta repos. For example, who's gonna manage the webhooks for that channel? Not to mention that I could see how having a half dozen or more webhooks in one channel could get extremely spammy seeing as I feel like support would be done in that channel as well. So if multiple people are working on their cogs and pushing things and people are also trying to get support, it would be easy to miss messages. Thus I feel like everyone having their own channel as long as they're on one of the lists would allow for better organization. I do like the idea of having them hidden behind a role that users could add to themselves though

**Comment by Chovin** [comment]
I give +1 to either solution, a separate cog support server or opt-in single-server.
Would the amount of channels be a concern?  especially as we get more approved repos.

the amount of approved repos should increase if we get this community more organized, communicating, and helping 26.

**Comment by Kowlin** [comment]
`Not to mention that I could see how having a half dozen or more webhooks in one channel`, this is all the choice for the channel owner.

**Comment by Twentysix26** [comment]
@Kowlin he means for the supposed beta channel, that has no actual "owner"

**Comment by Kowlin** [comment]
No webhooks for them ;)

**Comment by palmtree5** [comment]
That completely throws out part of the point of this entire discussion then, doesn't it?

> Once a repo is on the list, the community would help moderate future additions and changes to those repos. This would best be accomplished by everyone on EITHER list having a channel with a webhook for their repo in this server

I thought part of the point of this was to help those on the beta list help each other improve. I am still of the opinion that each repo on either list should have a channel and that webhooks would be the best way of seeing new changes for each repo outside of manually having to check each repo since webhooks would put it inside Discord

**Comment by Chovin** [comment]
hm. thank you for bringing us back on track.
I'm trying to think of a way to deal with the possibly vast number of channels.
maybe there could be multiple roles you could self-add, one for approved cog support/development, one for beta.

another issue is community moderation.
One of the larger things that gets factored in when deciding which repo gets into approved is how much we trust the author.
the Beta list is less moderated on the "you're a generally nice guy that respects others" department.
Would having people we aren't as familiar with moderating their own channels away from the eyes of the staff/dev detract from the community at all?

is this a legitimate concern?

keeping it as separate servers means there is no obligation for staff/ the dev to help moderate and make sure the environment is nice n friendly.

**Comment by Redjumpman** [comment]
Just want to help illustrate a point. My repo gets used a lot, and I usually wake up to atleast 12-17 DMs a day asking questions or wanting help because I messed something up and need to fix it in my code. Propagating that traffic to the cog server is a clean way to resolve that issue. I am sure other creators have had similar experiences. I think letting people know in the welcome message on the main server would help too. 

Having roles that unlock support channels would def create role stacking, and causes another bit of education. Now you have to tell someone to assign themselves the role and how to do it so they can ask their question, whereas it is easier to join the cog server and find the channel. Then if they download a cog from another author they dont need to add another role to get support. Also kowlin is right people love fake internet achievements and roles feel like that to some people.

Let's talk about the approved list again. A normal user has no idea what something on the approved list even means. And it should mean something to them and to those who are on the beta list. Currently no reason for someone like @palmtree5 to apply or do anything to his code,  because users will still download his cogs. Should get benefits for being on the list, and I say that as someone who probably doesn't even deserve to be on the approved list. 

I still think a community manager, elected by the community(as suggested by irdumb) approved by 26 and co could help to do a lot of this stuff. Maybe have that person talk to 26 and staff once a month about what is happening under the hood for red bot and do a post in #News or something telling everyone what is going on this month.

**Comment by skeith** [comment]
How about this. 
Approved repo get their own channel, while beta repo get two channels. One support, one megaphones for web hooks

**Comment by Chovin** [comment]
please clarify. do you mean
each user on approved list gets a channel to themselves but everyone on beta list shares only 2 channels? so that means would give us 10 new channels currently.

**Comment by Redjumpman** [comment]
Just need two new channels. One that only shows updates  to approved list repos using webhooks No write access. And another channel that shows News. Write access restricted to CM (community manager) and staff, but users can react to the post.

**Comment by Chovin** [comment]
but we'd keep the separate server in addition to this right?
otherwise there wouldn't be a place for development. also I would only really care to see updates from the cogs I use as well as the occasional spotlight if I was a user.

I'm still in agreement with one of palm's points:

> I thought part of the point of this was to help those on the beta list help each other improve. I am still of the opinion that each repo on either list should have a channel and that webhooks would be the best way of seeing new changes for each repo outside of manually having to check each repo since webhooks would put it inside Discord

**Comment by Redjumpman** [comment]
Yeah we would keep the second server because it provides a good forum for support questions. Once you get enough people using your cogs, simple questions asked in your channels, can be answered by others in your channel. At that point you have started your own little sub community which is really cool. 

Having the hooks in the main server for approved list doesnt detract from this. It just increases visability for those people and really shows that Red does approve of these repos. I think palm was referencing having both of these things. What we have in the second server plus what I mentioned.

**Comment by Twentysix26** [comment]
After some thought I think it would probably be better to keep the support channels in the other server. Plus I like the current structure. We can give it visibility by putting the invite in custom commands / channel topics / etc and redirect users who have issues with 3rd party cogs there. We could add a channel in the main server for cog/repo spotlights or whatever.  
I also want to listen to Jenn's input on this since she deals with most of the community stuff and I assume she hasn't read any of this yet. I'll ~~pester her to read~~ link her this issue today/tomorrow.  
**Is there anything in particular that you'd like to hear our input on?** You really don't need us to approve every little thing, like I said I'm on board with most of the ideas being thrown here and you are free to  organize it as you'd like.

**Comment by Kowlin** [comment]
I'd love to see on what she thinks of the community spotlight. We've seen 2 ideas so far. I'm mostly going for the spotlight per week or month. But I got a feeling that this can be better.

**Comment by MiniJennJenn** [comment]
Ok. So, I made a stupid github account just to comment on this. 

I like the idea of cog creators having the ability to "vote" or "vouch" for new repos. I think we all like each other and respect each other as coders/reasonable people. So, I believe current cog creators would be a solid group of people who can detect quality code written by non-toxic members of the community. This would also be helpful on the grounds that it would remove a lot of the burden from 26. As long as he agrees to prioritize looking at it once everyone comes to a consensus on it. However, we do need to figure out a system of votes and someone to organize it and bring one that passes inspection and approval to 26's attention. 

I am entirely with 26 on the point of the multiple servers. We're in a weird place because having two servers feels fragmented to me and frankly I have the cog server muted. But at the same time, having too many channels would be a little crazy and if anything there's even more channels in the cog support server. I think we'll have to continue working on this point to find a better solution, but I suppose this is a lower priority issue until a different solution is presented. And the current system really isn't too bad. 

As for cog community spotlight/advertising, it actually sounds like a pretty good idea. Doable with only one additional channel (I don't think it should go in #announcements though) - and I think this should be a channel in the main server with a link to the cog support server. Also, if you wanted me to, I could help do that since I'm pretty unbiased and I know nothing about coding so I can pick out what the average user would like and word it for them. On top of what is picked out or curated, maybe you guys could each pick one cog you're particularly proud of and send it in and I'll make a post every x days in the channel to advertise a different coder/cog? We can do the different "themes" or whatever. I also think it would be ok to keep up the old spotlights which would more or less make it become a hall of fame type. I don't think it would take up much time so I'm willing to do it (but ofc someone else can do this if they want). 

As for beta repos, sure make them a channel in the cog support server for them to help each other or whatever you were thinking. But, I think they can make do with sharing one location to help each other until they get approved. I'm not entirely clear what this whole discussion about beta channels was about, but I think they're not a priority until we figure out everything else. 

As for a news channel or something - maybe a good idea in the cog support server. Maybe every cog creator is allowed to use it but only for important announcements regarding their repo. 

On a side note, I have now edited >repos to include a link to the cog support server. 

This seems like a good place to start. In summary, cog creator vouching system yes (needs organization/leader), cog spotlight yes, current 2 server system sure (with more links to it), beta people can make do on their own for now.

**Comment by Redjumpman** [comment]
Awesome feedback on all of this. +1111 for adding the link to >repos. I totally get the fractured community part, and while I can't speak for everyone, I have found great success in having people post in my channel so far. It's really great, and it's a place for cog creators to talk to each other about cog creation, improving Red, and sharing techniques, etc.

The news portion was something that I thought should be Red bot core cogs only. Like maybe a once a month inside access to what 26, Will, Irdumbs, Ely, Jenn are up to in regards to Red bot. Someone from Staff or a CM(Community Manger) could ask questions and get responses about what is going on under the hood, what blockers Red has atm, New features, etc. Questions could be limited(2 or 3) and limited to patrons only, but the channel can be viewed by everyone. I really enjoy reading Dev blogs for games that I play in early access or something I am waiting to release.

As for a cog creators "Leader" I guess we could elect someone out of our group. I think Kowlin would be great, and already has all the rights. So there is my vote.

**Comment by Chovin** [comment]
A leader? Shoot. I'd vote for Kowlin also.

I think Jenn would be a great spotlight writer. At least in the interim. Don't want to hog all her stuDYING time.

I like that idea of dev blogs channel too. Kinda like #announcements but more development news and less "you should probably update". Probably should be semi-curated like a blog instead of just a chat room. Maybe could put it on the docs so that it doesn't clutter the chat and it might feel like a better environment for that type of thing? /shrug
This dev blog thing would give more incentive for people to patron too  ;)

About cog creators helping 26, we just gotta make sure we keep choosing respectful people that can code more or less for cog creators. A cog in Red could notify 26 once x number of cog creators have :+1:'d an application/issue/pr, whatever they'd end up helping with.

Alright! Thank you everyone for participating in this discussion!
Shall we start implementing some of these things? The cog-support server seems like it's going pretty well. We'll just need to link it some more as Jenn was saying.

What should be the 1st spotlight?  I nominate Orels1's drawing cog :3
Would be a cool "interview" if we're going that deep.

**Comment by Redjumpman** [comment]
This is wonderful. And for the dev blog/news channel it should be chat restricted but have reactions so people can react to the curated blog, and move the discussion to general or other appropriate chats. Also I second Orel1's Drawing cog for first slot. :D I see what I can do about making a cog to track Thumbs up % for repos. Maybe I can lay down the ground work and some of our more experienced coders can make it better.

**Comment by Chovin** [comment]
That sounds great Jump, make a PR early so we can code review please.

I vote we put the dev blog on the docs or combine the spotlights and the dev-blog into one #dev-blog channel :) 
👍 on reactions

**Comment by MiniJennJenn** [comment]
In response to "ask questions and get responses about what is going on under the hood, what blockers Red has atm, New features, etc.". Even I don't know what's going on under the hood x). If anything, I just act as a community manager for the main server and maintain the flow of society. 

I'm just afraid that if there's an open question dev-blog, people will ask questions which lead to more questions and it'll take up a lot of time for 26 or whomever to answer. The public is voracious and selfish when it comes to getting their questions answered. Maybe only patrons who pay a certain amount should get this perk - the privelege to ask questions hehe. (GREAT IDEA). 

I can work on orels for the first one. However, if you guys want to make it easier on me - if each person picked one cog and "presented" it to me, I could definitely stockpile enough for a few months
its not that much work for people who obviously know what their own cogs do and how to use them  to write to pick the one they like the most. If I just put out one or two a week, I'll have plenty. Once we have final approval and figured out the channel name/how it'll work I'll use that one first.

**Comment by Redjumpman** [comment]
One a week is enough I think. I think patrons who donate X amount to submit questions per month, and then you pick which questions you want to send to 26, and limit it to a certain number. Was thinking that the devblog would be like: 

"This month with red bot 26 decided to create helper classes for file IO. These are designed at helping content creators do things~~Will has been chipping away at audio, in particular he has been trying to redesign X system to better do this thing. ~~Irdumbs has been working on a tutorial to help new bot owners explore all the wonderful features in Red that we enjoy. @patrondonator asks "This question is for Will. Any chance you could add mix tables to Audio.py? Would really like to show off my DJ skills in my server. Will: It would be really hard to add this feature. Maybe down the road we can look at implementing something like that. Audio is a really big cog, and some bots are dedicated to only doing that one thing, so we are trying to polish and fix it's core functions before adding new features. But we always like receiving new and fresh ideas." Well that's all we have for this month. Special thanks to all our patrons that help make these dev blogs possible, and if you would like the opportunity to have your question answered or just want to support us you can donate here: [patron link]. 

I'll ping all the cog creators in the second server to day. Would like to hear what @palmtree5 @Kowlin @axios, @Chovin, and all our other cog creators have to say. Big shout out and thanks to @MiniJennJenn and @Twentysix26 for agreeing to work with these ideas. :D

**Comment by Kowlin** [comment]
I actually like the idea of me being the primary person to approach on for coding advice. For the blog, its a interesting idea. Quite like it. Better then the "Here we have a cog in a spotlight. Enjoy!!". This will give some great insight to the outside world on what we're doing and where we are expanding our work on.

I also think that the end user can also ask questions without being a patreon. This will avoid people mass DM'ing other cog creators to have their question included. Maybe a Google Survey will do the trick for this just fine, or well... We all code. We might as well create a cog for it. and go through the questions once a week or month. Depending on when we want to launch the blog post.

Also another off-topic: I've been looking into making a Google Survey for Red, if someone is interested in helping me with that. Feel free to shoot me a DM or Mention somewhere on Discord.

**Comment by Chovin** [comment]
if we do a blog on the docs, Kowlin, are you willing to manage it? 
Are we combining the cog spotlights with the dev blog?

if we do have a #dev-blog / spotlight channel, it should only be writable by Jenn/26, _maybe_ staff imo.
If you want questions submittable by everyone, maybe have patron's questions be higher priority? should give back to them somehow.
How would people submit questions?

Once the other cog creators have put in their opinions, let's start wrapping things up.

**Comment by Kowlin** [comment]
Ye I think I can manage Jekyll to do so, but I think keeping them in the Discord server will lead to higher user retention. And Patrons should have a higher priority.

**Comment by skeith** [comment]
Maybe also post some kind of cog making tutorial :wink:

**Comment by Chovin** [comment]
that is a separate discussion. let's keep it on track and get some of these things moving ;)
here, I made an issue for us to discuss there later if you'd like #52

**Comment by Redjumpman** [comment]
Two channels. Spotlights are separate from dev blogs. Both have enough specific content to warrant their own channels. Both should be writable by 26, Jenn, and staff(?) or a CM if we elect one. I think questions could be submitted through a cog, or we could start a new issue each month where people can post their questions, but that would be hard considering no way to stop patrons only from posting. The cog could detect the role, and accept only from those individuals. Maybe output to a google docs or something for Jenn to read later.

**Comment by palmtree5** [comment]
For the question bout how to go about submitting questions: maybe someone writes a cog that users can submit questions via a command (potentially PM?) and does checks for a) if the user is in the main server and b) their role in the main server (for determining priority)

**Comment by palmtree5** [comment]
So I threw this together though if you try to ask questions through any server that isn't the main server, it errors at the moment (though I would think questions would be asked through the main server. Right now the server id in the `getquestions` command is the cog support server's id but that will change to the server id for the main server at some point.

I'm probably gonna get yelled at for hardcoding values, aren't I...

EDIT: Didn't link the gist lol https://gist.github.com/palmtree5/3aca9b182f4db339b15356139e7e0bd3
