### ISSUE TITLE
Better_application tracking

### ISSUE THREAD

**Issue by Redjumpman** [Twentysix26/Red-Docs#53]
We should move applications to a separate repo that allows users wishing to create a repo for the first time to just fork the repo. The repo will contain any tools to help them get started to become a Cog Creator. Once they feel their repo is ready, they can PR to this repo, and we can review their changes. This works better than issues, because we can have people approve changes.

The second thing is that we can see what happens to the code after acceptance. Easier way to track malicious code injection. This has been something we have been trying to remedy for a while.

The PR's never close, but can be organized. We can really get organized by using integrations like zenhub and make it look pretty. Thoughts?

_No pandentias were harmed in the making of better_application._

**Comment by NekoTony** [comment]
> No pandentias were harmed in the making of better_application.
Lol

Anyways, i think this is a wonderful idea but over complicating the system. Anyways, i'm down with you.

**Comment by Chovin** [comment]
😂 
oh man
anyways, I think this is a great idea and drastically uncomplicates the application process, awareness afterwards, and accessibility for new cog creators.
having the code reviews and commits in one timeline would really help 👍 
like Jump said, we wouldn't merge these PRs, just keep them open and label appropriately.

The repo can be made to be the correct 3rd party repo format as well as include some common use-case cog examples as well as, in the future, full tutorials traversable via git tags (like various other popular tutorials).

I prefer ZenHub over Projects since it seems more functional and easy to use. We can always use labels as fallback if people don't have ZenHub.
