### ISSUE TITLE
Linux Documentation

### ISSUE THREAD

**Issue by Kowlin** [Twentysix26/Red-Docs#78]
Enhance the docs with a new Linux template for installation and cover the docs with the following distributions

Distributions:
- [x] Alpine
- [x] Archlinux
- [x] CentOS
- [ ] Debian
- [x] Fedora
- [x] Ubuntu

Template:
- [ ] Linux install docs template.

@palmtree5

**Comment by Kowlin** [comment]
Archlinux install template: 
```bash
pacman -S python python-pip git ffmpeg base-devel openssl libffi libsodium
git clone -b develop --single-branch https://github.com/Twentysix26/Red-DiscordBot.git
cd Red-DiscordBot
python launcher.py
```

**Comment by Kowlin** [comment]
Alpine install template:
```bash
apk add python3-dev ffmpeg git openssl libffi-dev libsodium-dev g++ make
git clone -b develop --single-branch https://github.com/Twentysix26/Red-DiscordBot.git
cd Red-DiscordBot
python3 launcher.py
```

**Comment by palmtree5** [comment]
Centos 7 install template (mostly from a script in https://github.com/Twentysix26/Red-DiscordBot/issues/649):
```
yum -y groupinstall development
yum -y install https://centos7.iuscommunity.org/ius-release.rpm
yum -y install yum-utils wget which python35u python35u-pip python35u-devel openssl-devel libffi-devel git opus-devel
sh -c "$(wget https://gist.githubusercontent.com/mustafaturan/7053900/raw/27f4c8bad3ee2bb0027a1a52dc8501bf1e53b270/latest-ffmpeg-centos6.sh -O -)"
git clone -b develop --single-branch https://github.com/Twentysix26/Red-DiscordBot.git Red-DiscordBot
cd Red-DiscordBot
python3.5 launcher.py
```

Tagging @pepsifire since they made the script I got these commands from.

EDIT: Compacted the yum commands down, though the ffmpeg compilation script installs a few more packages by itself

**Comment by Kowlin** [comment]
Not a fan of the above template, seems like something that could just be taken in one go, especially due the fact that we can just use ``libavtools`` for this and call it a day

**Comment by skeith** [comment]
The centos template was made as a complete Red installs hence there is pip stuff (while Kowlin' alpine and archlinux does not list pip stuff) - do correct me if launcher.py able to installs pip

The script uses ffmpeg since that was what I did. I did not know that we can use libavtools.

To further shorten it, just create sh script for all those stuff and run it in one go.

**Comment by Kowlin** [comment]
@skeith Pip is included in python3-dev for some magic reason ;)

**Comment by TeemoTheYiffer** [comment]
Regarding Debian, Jessie iteration comes with Python2.7 native and 3.4 upgrade-able. Upgrade to the latest Test iteration: Stretch (Guide: https://linuxconfig.org/how-to-upgrade-debian-8-jessie-to-debian-9-stretch). That comes with Python3.5 support. In my case, I had to build Python3.5 since my router had a 2.x Linux kernel and Stretch needs the latest libc6 which needed a 3.4.x+ kernel. 

#To search kernels 
sudo apt-get install linux-image-flavour  
#Then pick one
apt-cache search linux-image

Here's the step sequence to build python3.5 within Jessie, albeit it'll take a while.

# Setup dependencies
apt-get install build-essential libc6-dev
apt-get install libncurses5-dev libncursesw5-dev libreadline6-dev
apt-get install libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev
apt-get install libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev

# Download and extract
cd $HOME
wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz
tar -zxvf Python-3.5.2.tgz

# Start to compile
cd Python-3.5.2
./configure

# My router has 2 processors, so entered that. Enter the number of processors after -j
make -j2
sudo make install 

# Remove to save space
cd ..
sudo rm -fr ./Python-3.5.2*

# Test
cd
python3 --version

# output: "Python 3.5.2"
pip3 list

# Update pip
pip3 install -U pip
pip3 install -U setuptools

**Comment by palmtree5** [comment]
@skeith the archlinux template includes installing pip

**Comment by palmtree5** [comment]
@Kowlin Problem with trying to install libavtools on centos: no package available

**Comment by Kowlin** [comment]
Well... Something along those lines. Will dig later tonight

**Comment by palmtree5** [comment]
Ubuntu 16.04 instructions:

```
sudo apt-get install python3.5-dev python3-pip build-essential libssl-dev libffi-dev git ffmpeg libopus-dev unzip -y
git clone https://github.com/Twentysix26/Red-DiscordBot
cd Red-DiscordBot
python3 launcher.py
```

**Comment by palmtree5** [comment]
Fedora 25 instructions:

```
dnf group install 'development tools'
dnf install wget redhat-rpm-config libffi-devel python3-devel
dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm
dnf install ffmpeg opus-devel
git clone https://github.com/Twentysix26/Red-DiscordBot
cd Red-DiscordBot
python3 launcher.py
```

**Comment by palmtree5** [comment]
Debian 8 instructions:

```
apt install nano
nano /etc/apt/sources.list
```
add `deb http://httpredir.debian.org/debian jessie-backports main contrib non-free` on its own line at the end of the file. Save and exit (Ctrl+X, y, Enter)

```
apt update
apt install build-essential libssl-dev libffi-dev git ffmpeg libopus-dev unzip -y
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
tar xvf Python-3.6.0.tgz
cd Python-3.6.0
./configure --enable-optimizations
make -j4
make altinstall
cd ..
wget https://bootstrap.pypa.io/get-pip.py
python3.6 get-pip.py
git clone https://github.com/Twentysix26/Red-DiscordBot
cd Red-DiscordBot
python3.6 launcher.py
```

**Comment by tilda** [comment]
For Debian I used pyenv/pyenv instead of the manual build steps.

Installing 3.6 would be like this:

```
pyenv install 3.6.0
pyenv global 3.6.0
pyenv rehash
```
This compiles 3.6, sets the python version via a `.python-version` file, and reloads pyenv's shims for the version change to take effect. (btw pip is included as pip3.6)

Note you need these packages:
```
build-essential libncursesw5-dev libreadline-dev libssl-dev libgdbm-dev libc6-dev libsqlite3-dev tk-dev libbz2-dev git unzip libffi-dev ffmpeg libopus-dev
```
for a full build with no warnings.

**Comment by Kowlin** [comment]
Annddd forgot to close this. :/
